// <auto-generated />
using System;
using FundraisingAppProcessor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FundraisingAppProcessor.Migrations
{
    [DbContext(typeof(FundraisingContext))]
    [Migration("20250130223815_MakeIdAutoIncrement")]
    partial class MakeIdAutoIncrement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FundraisingAppProcessor.Models.MoneyBox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ApprovedByAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateReturned")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MoneyBoxes");
                });

            modelBuilder.Entity("FundraisingAppProcessor.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FundraisingAppProcessor.Models.MoneyBox", b =>
                {
                    b.OwnsOne("FundraisingAppProcessor.Models.Denominations", "Denominations", b1 =>
                        {
                            b1.Property<int>("MoneyBoxId")
                                .HasColumnType("int");

                            b1.Property<int>("Count1")
                                .HasColumnType("int");

                            b1.Property<int>("Count10")
                                .HasColumnType("int");

                            b1.Property<int>("Count100")
                                .HasColumnType("int");

                            b1.Property<int>("Count10gr")
                                .HasColumnType("int");

                            b1.Property<int>("Count1gr")
                                .HasColumnType("int");

                            b1.Property<int>("Count2")
                                .HasColumnType("int");

                            b1.Property<int>("Count20")
                                .HasColumnType("int");

                            b1.Property<int>("Count200")
                                .HasColumnType("int");

                            b1.Property<int>("Count20gr")
                                .HasColumnType("int");

                            b1.Property<int>("Count2gr")
                                .HasColumnType("int");

                            b1.Property<int>("Count5")
                                .HasColumnType("int");

                            b1.Property<int>("Count50")
                                .HasColumnType("int");

                            b1.Property<int>("Count500")
                                .HasColumnType("int");

                            b1.Property<int>("Count50gr")
                                .HasColumnType("int");

                            b1.Property<int>("Count5gr")
                                .HasColumnType("int");

                            b1.Property<string>("OtherCurrencies")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("MoneyBoxId");

                            b1.ToTable("MoneyBoxes");

                            b1.WithOwner()
                                .HasForeignKey("MoneyBoxId");
                        });

                    b.Navigation("Denominations")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
